<?php

/**
 * Sample configuration file.
 * Copy this to config.php and fill in your values.
 * config.php is auto-generated by the installer.
 *
 * @license MIT
 */

// ── Database ──────────────────────────────────────────────────────────────
define('DB_HOST',     'localhost');
define('DB_PORT',     '3306');
define('DB_NAME',     'rsa21');
define('DB_USER',     'root');
define('DB_PASS',     '');
define('DB_CHARSET',  'utf8mb4');

// ── Application ───────────────────────────────────────────────────────────
define('APP_NAME',     'RSA21-Free');
define('APP_URL',      'http://localhost');
define('APP_KEY',      'change-me-32-chars-secret-key!!');   // min 32 chars
define('APP_DEBUG',    false);
define('APP_TIMEZONE', 'Europe/Berlin');
define('APP_LOCALE',   'de_DE');
define('APP_VERSION',  '1.0.0');

// ── Session ───────────────────────────────────────────────────────────────
define('SESSION_LIFETIME', 7200);      // seconds
define('SESSION_NAME',     'RSA21_SESSION');

// ── Mail ──────────────────────────────────────────────────────────────────
define('SMTP_HOST',      '');
define('SMTP_PORT',      587);
define('SMTP_USER',      '');
define('SMTP_PASS',      '');
define('SMTP_FROM',      'noreply@example.com');
define('SMTP_FROM_NAME', 'RSA21-Free');
define('SMTP_ENCRYPTION','tls');       // tls | ssl | ''

// ── Security ──────────────────────────────────────────────────────────────
define('MAX_LOGIN_ATTEMPTS',  5);
define('LOGIN_LOCKOUT_TIME',  900);    // seconds
define('PASSWORD_MIN_LENGTH', 8);
define('TWO_FACTOR_ENABLED',  false);
define('REGISTRATION_ENABLED', true);

// ── Uploads ───────────────────────────────────────────────────────────────
define('UPLOAD_MAX_SIZE',   52428800); // 50 MB in bytes
define('UPLOAD_PATH',       BASE_PATH . '/dateien');
define('ALLOWED_EXTENSIONS', ['svg','png','jpg','jpeg','pdf','zip','dxf']);

// ── Logging ───────────────────────────────────────────────────────────────
define('LOG_LEVEL',    'info');        // debug | info | warning | error
define('LOG_PATH',     BASE_PATH . '/infos');

// ── Backup ────────────────────────────────────────────────────────────────
define('BACKUP_PATH',  BASE_PATH . '/sicherungen');

// ── Storage ───────────────────────────────────────────────────────────────
define('STORAGE_PATH', BASE_PATH . '/speicher');

// ── PDF ───────────────────────────────────────────────────────────────────
define('PDF_AUTHOR',   APP_NAME);
define('PDF_CREATOR',  APP_NAME . ' v' . APP_VERSION);
