<?php

use App\Core\CSRF;
use App\Core\View;

require_once VIEWS_PATH . '/_helpers.php';

$settings = is_array($settings ?? null) ? $settings : [];
?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h1 class="h2 mb-1">Einstellungen</h1><p class="text-body-secondary mb-0">Konfigurieren Sie Firma, PDF, E-Mail, Sicherheit und rechtliche Hinweise.</p></div><a href="/settings/smtp-test" class="btn btn-outline-primary"><i class="bi bi-envelope-check me-2"></i>SMTP testen</a></div>
<form method="post" action="/settings" enctype="multipart/form-data">
    <?= CSRF::field() ?>
    <ul class="nav nav-tabs"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#company-tab" type="button">Firma</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#pdf-tab" type="button">PDF</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#mail-tab" type="button">E-Mail</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#security-tab" type="button">Sicherheit</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#legal-tab" type="button">Rechtliches</button></li></ul>
    <div class="tab-content border border-top-0 rounded-bottom p-4 bg-body">
        <div class="tab-pane fade show active" id="company-tab"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="company_name">Firmenname</label><input class="form-control" id="company_name" name="settings[company_name]" value="<?= View::e((string) rsa21_setting($settings, 'company_name')) ?>"></div><div class="col-md-6"><label class="form-label" for="company_logo">Logo (Pfad)</label><input class="form-control" id="company_logo" name="settings[company_logo]" value="<?= View::e((string) rsa21_setting($settings, 'company_logo')) ?>"></div><div class="col-12"><label class="form-label" for="company_address">Adresse</label><textarea class="form-control" id="company_address" name="settings[company_address]" rows="3"><?= View::e((string) rsa21_setting($settings, 'company_address')) ?></textarea></div><div class="col-md-6"><label class="form-label" for="company_phone">Telefon</label><input class="form-control" id="company_phone" name="settings[company_phone]" value="<?= View::e((string) rsa21_setting($settings, 'company_phone')) ?>"></div><div class="col-md-6"><label class="form-label" for="company_email">E-Mail</label><input class="form-control" id="company_email" name="settings[company_email]" value="<?= View::e((string) rsa21_setting($settings, 'company_email')) ?>"></div><div class="col-md-6"><label class="form-label" for="company_website">Website</label><input class="form-control" id="company_website" name="settings[company_website]" value="<?= View::e((string) rsa21_setting($settings, 'company_website')) ?>"></div><div class="col-md-6"><label class="form-label" for="company_logo_upload">Logo hochladen</label><input class="form-control" type="file" id="company_logo_upload" name="company_logo_upload" accept="image/*"></div></div></div>
        <div class="tab-pane fade" id="pdf-tab"><div class="row g-3"><div class="col-12"><label class="form-label" for="pdf_footer_text">Fußzeile</label><input class="form-control" id="pdf_footer_text" name="settings[pdf_footer_text]" value="<?= View::e((string) rsa21_setting($settings, 'pdf_footer_text')) ?>"></div><div class="col-md-4"><label class="form-label" for="pdf_page_size">Seitengröße</label><select class="form-select" id="pdf_page_size" name="settings[pdf_page_size]"><option value="A4" <?= rsa21_setting($settings, 'pdf_page_size', 'A4') === 'A4' ? 'selected' : '' ?>>A4</option><option value="A3" <?= rsa21_setting($settings, 'pdf_page_size', 'A4') === 'A3' ? 'selected' : '' ?>>A3</option></select></div><div class="col-md-4"><label class="form-label" for="pdf_orientation">Ausrichtung</label><select class="form-select" id="pdf_orientation" name="settings[pdf_orientation]"><option value="P" <?= rsa21_setting($settings, 'pdf_orientation', 'P') === 'P' ? 'selected' : '' ?>>Hochformat</option><option value="L" <?= rsa21_setting($settings, 'pdf_orientation', 'P') === 'L' ? 'selected' : '' ?>>Querformat</option></select></div><div class="col-md-4"><label class="form-label" for="company_logo_pdf">PDF-Logo</label><input class="form-control" id="company_logo_pdf" name="settings[company_logo_pdf]" value="<?= View::e((string) rsa21_setting($settings, 'company_logo_pdf')) ?>"></div><div class="col-12"><label class="form-label" for="company_logo_pdf_upload">PDF-Logo hochladen</label><input class="form-control" type="file" id="company_logo_pdf_upload" name="company_logo_pdf_upload" accept="image/*"></div></div></div>
        <div class="tab-pane fade" id="mail-tab"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="smtp_host">SMTP-Host</label><input class="form-control" id="smtp_host" name="settings[smtp_host]" value="<?= View::e((string) rsa21_setting($settings, 'smtp_host')) ?>"></div><div class="col-md-3"><label class="form-label" for="smtp_port">Port</label><input class="form-control" id="smtp_port" name="settings[smtp_port]" value="<?= View::e((string) rsa21_setting($settings, 'smtp_port')) ?>"></div><div class="col-md-3"><label class="form-label" for="smtp_encryption">Verschlüsselung</label><select class="form-select" id="smtp_encryption" name="settings[smtp_encryption]"><option value="tls" <?= rsa21_setting($settings, 'smtp_encryption', 'tls') === 'tls' ? 'selected' : '' ?>>TLS</option><option value="ssl" <?= rsa21_setting($settings, 'smtp_encryption', 'tls') === 'ssl' ? 'selected' : '' ?>>SSL</option><option value="none" <?= rsa21_setting($settings, 'smtp_encryption', 'tls') === 'none' ? 'selected' : '' ?>>Keine</option></select></div><div class="col-md-6"><label class="form-label" for="smtp_user">Benutzername</label><input class="form-control" id="smtp_user" name="settings[smtp_user]" value="<?= View::e((string) rsa21_setting($settings, 'smtp_user')) ?>"></div><div class="col-md-6"><label class="form-label" for="smtp_pass">Passwort</label><input class="form-control" id="smtp_pass" name="settings[smtp_pass]" type="password" value="<?= View::e((string) rsa21_setting($settings, 'smtp_pass')) ?>"></div><div class="col-md-6"><label class="form-label" for="smtp_from">Absender-E-Mail</label><input class="form-control" id="smtp_from" name="settings[smtp_from]" value="<?= View::e((string) rsa21_setting($settings, 'smtp_from')) ?>"></div><div class="col-md-6"><label class="form-label" for="smtp_from_name">Absendername</label><input class="form-control" id="smtp_from_name" name="settings[smtp_from_name]" value="<?= View::e((string) rsa21_setting($settings, 'smtp_from_name')) ?>"></div></div></div>
        <div class="tab-pane fade" id="security-tab"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="registration_enabled">Registrierung</label><select class="form-select" id="registration_enabled" name="settings[registration_enabled]"><option value="1" <?= rsa21_setting($settings, 'registration_enabled', '1') === '1' ? 'selected' : '' ?>>Erlaubt</option><option value="0" <?= rsa21_setting($settings, 'registration_enabled', '1') === '0' ? 'selected' : '' ?>>Deaktiviert</option></select></div><div class="col-md-6"><label class="form-label" for="twofa_enabled">2FA</label><select class="form-select" id="twofa_enabled" name="settings[2fa_enabled]"><option value="1" <?= rsa21_setting($settings, '2fa_enabled', '0') === '1' ? 'selected' : '' ?>>Aktiv</option><option value="0" <?= rsa21_setting($settings, '2fa_enabled', '0') === '0' ? 'selected' : '' ?>>Inaktiv</option></select></div></div></div>
        <div class="tab-pane fade" id="legal-tab"><div class="row g-3"><div class="col-12"><label class="form-label" for="legal_disclaimer">Rechtlicher Hinweis</label><textarea class="form-control" id="legal_disclaimer" name="settings[legal_disclaimer]" rows="8"><?= View::e((string) rsa21_setting($settings, 'legal_disclaimer')) ?></textarea></div></div></div>
    </div>
    <div class="d-flex justify-content-end mt-4"><button type="submit" class="btn btn-primary">Einstellungen speichern</button></div>
</form>
