<?php

use App\Core\CSRF;
use App\Core\View;

require_once VIEWS_PATH . '/_helpers.php';

$backups = rsa21_data_list($backups ?? []);
?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h1 class="h2 mb-1">Backup</h1><p class="text-body-secondary mb-0">Sichern und restaurieren Sie Datenbank und Dateibestände.</p></div><form method="post" action="/backup/create"><?= CSRF::field() ?><button type="submit" class="btn btn-primary"><i class="bi bi-database-add me-2"></i>Backup erstellen</button></form></div>
<div class="row g-4"><div class="col-lg-8"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="h5 mb-0">Verfügbare Backups</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Datei</th><th>Datum</th><th>Größe</th><th class="text-end">Aktionen</th></tr></thead><tbody><?php if ($backups === []): ?><tr><td colspan="4" class="text-center text-body-secondary py-5">Keine Backups vorhanden.</td></tr><?php endif; ?><?php foreach ($backups as $backup): ?><?php $filename = (string) rsa21_data_get($backup, 'filename', rsa21_data_get($backup, 'name', 'backup.zip')); ?><tr><td class="fw-semibold"><?= View::e($filename) ?></td><td><?= rsa21_date(rsa21_data_get($backup, 'created_at', rsa21_data_get($backup, 'date', ''))) ?></td><td><?= rsa21_filesize(rsa21_data_get($backup, 'size', 0)) ?></td><td class="text-end"><div class="btn-group"><a href="/backup/download/<?= rawurlencode($filename) ?>" class="btn btn-sm btn-outline-primary">Download</a><form method="post" action="/backup/delete/<?= rawurlencode($filename) ?>"><?= CSRF::field() ?><button type="submit" class="btn btn-sm btn-outline-danger">Löschen</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-lg-4"><div class="card shadow-sm"><div class="card-header"><h2 class="h5 mb-0">Backup wiederherstellen</h2></div><div class="card-body"><form method="post" action="/backup/restore" enctype="multipart/form-data" class="row g-3"><?= CSRF::field() ?><div class="col-12"><label for="backup_file" class="form-label">Backup-Datei</label><input type="file" class="form-control" id="backup_file" name="backup_file" required></div><div class="col-12 d-grid"><button type="submit" class="btn btn-outline-primary">Wiederherstellen</button></div></form></div></div></div></div>
