<?php

use App\Core\CSRF;
use App\Core\View;

require_once VIEWS_PATH . '/_helpers.php';

$materials = rsa21_data_list($materials ?? []);
$filters = rsa21_data_list($filters ?? []);
?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h1 class="h2 mb-1">Material</h1><p class="text-body-secondary mb-0">Bestände, Kategorien und Preislisten für Ihr Materiallager.</p></div><a href="/materials/create" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Neues Material</a></div>
<div class="card shadow-sm mb-4"><div class="card-body"><form method="get" action="/materials" class="row g-3 align-items-end"><?= CSRF::field() ?><div class="col-md-8"><label for="material-search" class="form-label">Suche</label><input type="search" class="form-control" id="material-search" name="search" value="<?= View::e((string) ($filters['search'] ?? '')) ?>" placeholder="Material, Artikelnummer oder Lieferant"></div><div class="col-md-4"><label for="category" class="form-label">Kategorie</label><input type="text" class="form-control" id="category" name="category" value="<?= View::e((string) ($filters['category'] ?? '')) ?>" placeholder="z. B. Schilder"></div><div class="col-12 d-flex justify-content-end"><button type="submit" class="btn btn-outline-primary">Filtern</button></div></form></div></div>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Kategorie</th><th>Name</th><th>Bestand</th><th>Mindestbestand</th><th>Einheit</th><th>Preis</th><th>Status</th><th class="text-end">Aktionen</th></tr></thead><tbody><?php if ($materials === []): ?><tr><td colspan="8" class="text-center text-body-secondary py-5">Keine Materialien vorhanden.</td></tr><?php endif; ?><?php foreach ($materials as $material): ?><?php $stock = (float) rsa21_data_get($material, 'stock', 0); $minStock = (float) rsa21_data_get($material, 'min_stock', 0); $indicator = $stock <= $minStock ? 'danger' : ($stock <= ($minStock * 1.25) ? 'warning' : 'success'); ?><tr><td><?= View::e((string) rsa21_data_get($material, 'category', '')) ?></td><td><div class="fw-semibold"><?= View::e((string) rsa21_data_get($material, 'name', 'Material')) ?></div><div class="small text-body-secondary"><?= View::e((string) rsa21_data_get($material, 'article_no', '')) ?></div></td><td><?= View::e(number_format($stock, 2, ',', '.')) ?></td><td><?= View::e(number_format($minStock, 2, ',', '.')) ?></td><td><?= View::e((string) rsa21_data_get($material, 'unit', 'Stk')) ?></td><td><?= rsa21_currency(rsa21_data_get($material, 'price', null)) ?></td><td><span class="badge text-bg-<?= View::e($indicator) ?> me-2">Bestand</span><?php if ($stock <= $minStock): ?><span class="badge text-bg-warning">Nachbestellen</span><?php endif; ?></td><td class="text-end"><a href="/materials/<?= View::e((string) rsa21_data_get($material, 'id', '')) ?>/edit" class="btn btn-sm btn-outline-secondary">Bearbeiten</a></td></tr><?php endforeach; ?></tbody></table></div></div>
