<?php

use App\Core\Auth;
use App\Core\CSRF;
use App\Core\View;

require_once VIEWS_PATH . '/_helpers.php';

$projects = rsa21_data_list($projects ?? []);
$filters = rsa21_data_list($filters ?? []);
$statusClasses = ['draft' => 'bg-secondary', 'active' => 'bg-primary', 'review' => 'bg-warning text-dark', 'completed' => 'bg-success', 'archived' => 'bg-dark'];
$statusLabels = ['draft' => 'Entwurf', 'active' => 'Aktiv', 'review' => 'In Prüfung', 'completed' => 'Abgeschlossen', 'archived' => 'Archiviert'];
$canCreate = Auth::hasRole('admin') || Auth::hasRole('editor') || Auth::hasPermission('projects.create');
?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h1 class="h2 mb-1">Projekte</h1><p class="text-body-secondary mb-0">Verwalten Sie alle Projekte inklusive Status, Fortschritt und Termine.</p></div><?php if ($canCreate): ?><a href="/projects/create" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Neues Projekt</a><?php endif; ?></div>
<div class="card shadow-sm mb-4"><div class="card-body"><form method="get" action="/projects" class="row g-3 align-items-end"><?= CSRF::field() ?><div class="col-md-8"><label for="search" class="form-label">Suche</label><input type="search" class="form-control" id="search" name="search" value="<?= View::e((string) ($filters['search'] ?? '')) ?>" placeholder="Projektname, Nummer oder Ort"></div><div class="col-md-4"><label for="status" class="form-label">Status</label><select class="form-select" id="status" name="status"><option value="">Alle Stati</option><?php foreach ($statusLabels as $value => $label): ?><option value="<?= View::e($value) ?>" <?= ($filters['status'] ?? '') === $value ? 'selected' : '' ?>><?= View::e($label) ?></option><?php endforeach; ?></select></div><div class="col-12 d-flex justify-content-end"><button type="submit" class="btn btn-outline-primary">Filtern</button></div></form></div></div>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Projekt</th><th>Status</th><th>Fortschritt</th><th>Zeitraum</th><th class="text-end">Aktionen</th></tr></thead><tbody><?php if ($projects === []): ?><tr><td colspan="5" class="text-center text-body-secondary py-5">Keine Projekte gefunden.</td></tr><?php endif; ?><?php foreach ($projects as $project): ?><?php $status = (string) rsa21_data_get($project, 'status', 'draft'); $progress = max(0, min(100, (int) rsa21_data_get($project, 'progress', 0))); ?><tr><td><div class="fw-semibold"><?= View::e((string) rsa21_data_get($project, 'title', 'Ohne Titel')) ?></div><div class="small text-body-secondary"><?= View::e((string) rsa21_data_get($project, 'project_number', '')) ?> · <?= View::e((string) rsa21_data_get($project, 'location', '')) ?></div></td><td><span class="badge <?= View::e($statusClasses[$status] ?? 'bg-secondary') ?>"><?= View::e($statusLabels[$status] ?? ucfirst($status)) ?></span></td><td><span class="badge text-bg-light"><?= View::e((string) $progress) ?> %</span></td><td><div><?= rsa21_date(rsa21_data_get($project, 'start_date', ''), 'd.m.Y') ?></div><div class="small text-body-secondary">bis <?= rsa21_date(rsa21_data_get($project, 'end_date', ''), 'd.m.Y') ?></div></td><td class="text-end"><div class="btn-group"><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>" class="btn btn-sm btn-outline-primary">Öffnen</a><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>/edit" class="btn btn-sm btn-outline-secondary">Bearbeiten</a></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php if (isset($pagination) && is_object($pagination) && method_exists($pagination, 'links')): ?><div class="mt-4 d-flex justify-content-center"><?= $pagination->links('/projects?page={page}') ?></div><?php endif; ?>
