<?php

use App\Core\View;

require_once VIEWS_PATH . '/_helpers.php';

$project = $project ?? [];
$plans = rsa21_data_list($plans ?? []);
$documents = rsa21_data_list($documents ?? []);
$uploads = rsa21_data_list($uploads ?? []);
$materials = rsa21_data_list($materials ?? []);
$photos = array_values(array_filter($uploads, static function ($upload): bool {
    $purpose = (string) rsa21_data_get($upload, 'purpose', '');
    $mime = (string) rsa21_data_get($upload, 'mime_type', '');
    return $purpose === 'photo' || str_starts_with($mime, 'image/');
}));
?>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><div class="text-body-secondary small"><?= View::e((string) rsa21_data_get($project, 'project_number', '')) ?></div><h1 class="h2 mb-1"><?= View::e((string) rsa21_data_get($project, 'title', 'Projekt')) ?></h1><p class="text-body-secondary mb-0"><?= View::e((string) rsa21_data_get($project, 'description', '')) ?></p></div><div class="d-flex gap-2"><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>/edit" class="btn btn-outline-secondary">Bearbeiten</a><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>/plans/create" class="btn btn-primary">Neuer Plan</a></div></div>
<ul class="nav nav-tabs"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#overview-tab" type="button">Übersicht</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#plans-tab" type="button">Pläne</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#documents-tab" type="button">Dokumente</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#uploads-tab" type="button">Uploads</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#materials-tab" type="button">Material</button></li></ul>
<div class="tab-content border border-top-0 rounded-bottom p-4 bg-body">
<div class="tab-pane fade show active" id="overview-tab"><div class="row g-4"><div class="col-lg-7"><div class="card h-100 shadow-sm"><div class="card-body"><h2 class="h5">Projektinformationen</h2><dl class="row mb-0"><dt class="col-sm-4">Ort</dt><dd class="col-sm-8"><?= View::e((string) rsa21_data_get($project, 'location', '—')) ?></dd><dt class="col-sm-4">Adresse</dt><dd class="col-sm-8"><?= View::e((string) rsa21_data_get($project, 'address', '—')) ?></dd><dt class="col-sm-4">Kontakt</dt><dd class="col-sm-8"><?= View::e((string) rsa21_data_get($project, 'contact_name', '—')) ?>, <?= View::e((string) rsa21_data_get($project, 'contact_phone', '—')) ?></dd><dt class="col-sm-4">E-Mail</dt><dd class="col-sm-8"><?= View::e((string) rsa21_data_get($project, 'contact_email', '—')) ?></dd><dt class="col-sm-4">Zeitraum</dt><dd class="col-sm-8"><?= rsa21_date(rsa21_data_get($project, 'start_date', ''), 'd.m.Y') ?> bis <?= rsa21_date(rsa21_data_get($project, 'end_date', ''), 'd.m.Y') ?></dd><dt class="col-sm-4">Priorität</dt><dd class="col-sm-8"><?= View::e((string) rsa21_data_get($project, 'priority', 'normal')) ?></dd></dl></div></div></div><div class="col-lg-5"><div class="card h-100 shadow-sm"><div class="card-body"><h2 class="h5">Standort</h2><?php if ((string) rsa21_data_get($project, 'gps_lat', '') !== '' && (string) rsa21_data_get($project, 'gps_lng', '') !== ''): ?><p class="mb-3"><?= View::e((string) rsa21_data_get($project, 'gps_lat')) ?>, <?= View::e((string) rsa21_data_get($project, 'gps_lng')) ?></p><a class="btn btn-outline-primary" href="https://www.google.com/maps?q=<?= View::e((string) rsa21_data_get($project, 'gps_lat')) ?>,<?= View::e((string) rsa21_data_get($project, 'gps_lng')) ?>" target="_blank" rel="noopener noreferrer"><i class="bi bi-geo-alt me-2"></i>In Karte öffnen</a><?php else: ?><p class="text-body-secondary mb-0">Für dieses Projekt sind keine GPS-Koordinaten hinterlegt.</p><?php endif; ?></div></div></div></div></div>
<div class="tab-pane fade" id="plans-tab"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Projektpläne</h2><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>/plans/create" class="btn btn-primary btn-sm">Neuer Plan</a></div><div class="list-group"><?php if ($plans === []): ?><div class="list-group-item text-body-secondary">Keine Pläne vorhanden.</div><?php endif; ?><?php foreach ($plans as $plan): ?><a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="/plans/<?= View::e((string) rsa21_data_get($plan, 'id', '')) ?>/editor"><div><div class="fw-semibold"><?= View::e((string) rsa21_data_get($plan, 'title', 'Plan')) ?></div><div class="small text-body-secondary">Maßstab <?= View::e((string) rsa21_data_get($plan, 'scale', '1:500')) ?> · Version <?= View::e((string) rsa21_data_get($plan, 'version', '1')) ?></div></div><span class="badge bg-secondary"><?= View::e((string) rsa21_data_get($plan, 'status', 'draft')) ?></span></a><?php endforeach; ?></div></div>
<div class="tab-pane fade" id="documents-tab"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Dokumente</h2><a href="/projects/<?= View::e((string) rsa21_data_get($project, 'id', '')) ?>/documents/create" class="btn btn-primary btn-sm">Neues Dokument</a></div><div class="list-group"><?php if ($documents === []): ?><div class="list-group-item text-body-secondary">Keine Dokumente vorhanden.</div><?php endif; ?><?php foreach ($documents as $document): ?><a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="/documents/<?= View::e((string) rsa21_data_get($document, 'id', '')) ?>"><div><div class="fw-semibold"><?= View::e((string) rsa21_data_get($document, 'title', 'Dokument')) ?></div><div class="small text-body-secondary"><?= View::e((string) rsa21_data_get($document, 'type', 'other')) ?></div></div><span class="badge bg-secondary"><?= View::e((string) rsa21_data_get($document, 'status', 'draft')) ?></span></a><?php endforeach; ?></div></div>
<div class="tab-pane fade" id="uploads-tab"><div class="row g-3 mb-4"><?php if ($photos === []): ?><div class="col-12"><div class="alert alert-light border text-body-secondary mb-0">Keine Fotos verfügbar.</div></div><?php endif; ?><?php foreach ($photos as $photo): ?><div class="col-12 col-md-6 col-xl-4"><div class="card shadow-sm h-100"><img src="/uploads/<?= View::e((string) rsa21_data_get($photo, 'id', '')) ?>" class="card-img-top" alt="Projektfoto"><div class="card-body"><div class="small text-body-secondary"><?= View::e((string) rsa21_data_get($photo, 'original_name', 'Foto')) ?></div></div></div></div><?php endforeach; ?></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Datei</th><th>Typ</th><th>Größe</th></tr></thead><tbody><?php if ($uploads === []): ?><tr><td colspan="3" class="text-center text-body-secondary">Keine Uploads vorhanden.</td></tr><?php endif; ?><?php foreach ($uploads as $upload): ?><tr><td><a href="/uploads/<?= View::e((string) rsa21_data_get($upload, 'id', '')) ?>" class="text-decoration-none"><?= View::e((string) rsa21_data_get($upload, 'original_name', 'Datei')) ?></a></td><td><?= View::e((string) rsa21_data_get($upload, 'purpose', rsa21_data_get($upload, 'file_type', 'Datei'))) ?></td><td><?= rsa21_filesize(rsa21_data_get($upload, 'file_size', 0)) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="tab-pane fade" id="materials-tab"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Material</th><th>Kategorie</th><th>Menge</th><th>Notiz</th></tr></thead><tbody><?php if ($materials === []): ?><tr><td colspan="4" class="text-center text-body-secondary py-4">Kein Material zugeordnet.</td></tr><?php endif; ?><?php foreach ($materials as $material): ?><tr><td><?= View::e((string) rsa21_data_get($material, 'name', 'Material')) ?></td><td><?= View::e((string) rsa21_data_get($material, 'category', '—')) ?></td><td><?= View::e((string) rsa21_data_get($material, 'pivot_quantity', '1')) ?> <?= View::e((string) rsa21_data_get($material, 'unit', 'Stk')) ?></td><td><?= View::e((string) rsa21_data_get($material, 'pivot_notes', '—')) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
